name: build

on:
  push:
    branches:
      - "**"
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golangci/golangci-lint-action@v8
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        with:
          source: .
          push: true
        env:
          # Only populate tag on a release
          IMAGE_TAG: "${{ github.event_name == 'release' && github.ref_name || '' }}"
          # Populate latest tag on main branch
          IMAGE_LATEST: "${{ github.ref_name == 'main' && 'latest' || '' }}"
          # Populate sha tag on every push
          IMAGE_SHA: "${{ github.sha }}"
