name: build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

permissions:
  packages: write
  contents: read

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: golangci/golangci-lint-action@v8
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        with:
          source: .
          push: true
        env:
          IMAGE_TAG: "${{ github.ref_name }}"
          IMAGE_SHA: "${{ github.sha }}"
